# Generated by Django 5.2.7 on 2026-02-18 07:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название филиала"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                (
                    "is_college",
                    models.BooleanField(default=False, verbose_name="Колледж"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Филиал",
                "verbose_name_plural": "Филиалы",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CollaborationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тип сотрудничества",
                "verbose_name_plural": "Типы сотрудничества",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Competency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("analytical", "Аналитические навыки"),
                            ("research", "Исследовательские навыки"),
                            ("quantitative", "Количественные методы"),
                            ("economic", "Экономические компетенции"),
                            ("financial", "Финансовые компетенции"),
                            ("technical", "Технические навыки"),
                            ("languages", "Языки"),
                            ("soft", "Мягкие навыки"),
                        ],
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компетенция",
                "verbose_name_plural": "Компетенции",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Methodology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Методология",
                "verbose_name_plural": "Методологии",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PublicationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тип публикации",
                "verbose_name_plural": "Типы публикаций",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResearchField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Категория"
                    ),
                ),
            ],
            options={
                "verbose_name": "Научное направление",
                "verbose_name_plural": "Научные направления",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="university",
        ),
        migrations.RemoveField(
            model_name="usercompetency",
            name="user",
        ),
        migrations.AddField(
            model_name="customuser",
            name="academic_degree",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Ученая степень"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата регистрации",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Студент"),
                    ("spo_student", "Студент колледжа (СПО)"),
                    ("bachelor", "Студент бакалавриата"),
                    ("master", "Студент магистратуры"),
                    ("postgraduate", "Аспирант"),
                    ("doctoral", "Докторант"),
                    ("lecturer", "Преподаватель"),
                    ("senior_lecturer", "Старший преподаватель"),
                    ("docent", "Доцент"),
                    ("professor", "Профессор"),
                    ("head_of_department", "Заведующий кафедрой"),
                    ("dean", "Декан факультета"),
                    ("researcher", "Научный сотрудник"),
                    ("senior_researcher", "Ведущий научный сотрудник"),
                    ("lab_assistant", "Лаборант"),
                    ("assistant", "Ассистент"),
                    ("methodist", "Методист"),
                ],
                max_length=50,
                null=True,
                verbose_name="Должность/Статус",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="projects_experience",
            field=models.TextField(
                blank=True,
                help_text="Расскажите о проектах, в которых вы участвовали",
                verbose_name="Опыт участия в проектах",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="publications_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество публикаций"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото для профиля",
                null=True,
                upload_to="avatars/",
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, max_length=1000, verbose_name="О себе"),
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="competencies",
        ),
        migrations.AddField(
            model_name="customuser",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.branch",
                verbose_name="Филиал",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="collaboration_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="users.collaborationtype",
                verbose_name="Типы сотрудничества",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название кафедры"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="users.branch",
                        verbose_name="Филиал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кафедра",
                "verbose_name_plural": "Кафедры",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.department",
                verbose_name="Кафедра",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="methodologies",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="users.methodology",
                verbose_name="Методологии",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="publication_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="users.publicationtype",
                verbose_name="Типы публикаций",
            ),
        ),
        migrations.CreateModel(
            name="QuestionnaireAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.CharField(blank=True, max_length=255, verbose_name="Филиал"),
                ),
                (
                    "study_program",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Специальность"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Должность"
                    ),
                ),
                (
                    "academic_degree",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ученая степень"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Кафедра"
                    ),
                ),
                (
                    "research_fields",
                    models.JSONField(default=list, verbose_name="Научные интересы"),
                ),
                (
                    "methodologies",
                    models.JSONField(default=list, verbose_name="Методологии"),
                ),
                (
                    "competencies",
                    models.JSONField(default=list, verbose_name="Компетенции"),
                ),
                (
                    "publications_count",
                    models.PositiveIntegerField(default=0, verbose_name="Публикации"),
                ),
                (
                    "publication_types",
                    models.JSONField(default=list, verbose_name="Типы публикаций"),
                ),
                (
                    "projects_experience",
                    models.TextField(blank=True, verbose_name="Опыт в проектах"),
                ),
                (
                    "collaboration_types",
                    models.JSONField(default=list, verbose_name="Типы сотрудничества"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата заполнения"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на анкету",
                "verbose_name_plural": "Ответы на анкеты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="research_fields",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="users.researchfield",
                verbose_name="Научные интересы",
            ),
        ),
        migrations.CreateModel(
            name="StudyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=20, verbose_name="Код специальности"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("spo", "СПО"),
                            ("bachelor", "Бакалавриат"),
                            ("master", "Магистратура"),
                            ("postgraduate", "Аспирантура"),
                        ],
                        max_length=20,
                        verbose_name="Уровень образования",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_programs",
                        to="users.branch",
                        verbose_name="Филиал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление подготовки",
                "verbose_name_plural": "Направления подготовки",
                "ordering": ["level", "name"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="study_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.studyprogram",
                verbose_name="Направление подготовки",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["branch"], name="users_custo_branch__934577_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["study_program"], name="users_custo_study_p_c4ace7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["position"], name="users_custo_positio_e363bb_idx"
            ),
        ),
        migrations.DeleteModel(
            name="University",
        ),
        migrations.DeleteModel(
            name="UserCompetency",
        ),
        migrations.AddField(
            model_name="customuser",
            name="competencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="users.competency",
                verbose_name="Компетенции",
            ),
        ),
    ]
