# Generated by Django 5.2.7 on 2026-03-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_middle_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("moderator", "Модератор"),
                    ("user", "Пользователь"),
                ],
                default="user",
                max_length=20,
                verbose_name="Роль в системе",
            ),
        ),
    ]
