# Generated by Django 5.2.7 on 2026-01-30 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.AlterModelOptions(
            name="projectmember",
            options={
                "ordering": ["-joined_at"],
                "verbose_name": "Участник проекта",
                "verbose_name_plural": "Участники проектов",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="Срок сдачи"),
        ),
        migrations.AddField(
            model_name="project",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="Только по приглашению",
                verbose_name="Закрытый проект",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("research_paper", "Научная статья"),
                    ("dissertation", "Диссертация"),
                    ("grant", "Грантовый проект"),
                    ("conference", "Подготовка к конференции"),
                    ("book", "Книга/Монография"),
                    ("creative", "Творческий проект"),
                    ("other", "Другое"),
                ],
                default="research_paper",
                max_length=50,
                verbose_name="Тип проекта",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="scientific_field",
            field=models.CharField(
                blank=True,
                help_text="Например: ИИ, Биоинформатика, Экономика",
                max_length=200,
                verbose_name="Научная область",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ключевые слова для поиска",
                verbose_name="Теги",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="can_create_tasks",
            field=models.BooleanField(
                default=True, verbose_name="Может создавать задачи"
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="can_delete_project",
            field=models.BooleanField(
                default=False, verbose_name="Может удалять проект"
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="can_edit_project",
            field=models.BooleanField(
                default=False, verbose_name="Может редактировать проект"
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="can_invite_members",
            field=models.BooleanField(
                default=False, verbose_name="Может приглашать участников"
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="can_manage_tasks",
            field=models.BooleanField(
                default=False, verbose_name="Может управлять задачами"
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_project_members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Приглашен пользователем",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="max_members",
            field=models.PositiveIntegerField(
                default=10,
                help_text="0 = без ограничений",
                verbose_name="Максимум участников",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("recruiting", "Набор участников"),
                    ("active", "Активный"),
                    ("completed", "Завершен"),
                    ("on_hold", "На паузе"),
                    ("archived", "В архиве"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("product_owner", "Product Owner (Научный руководитель)"),
                    ("scrum_master", "Scrum Master (Менеджер проекта)"),
                    ("lead_researcher", "Lead Researcher (Ведущий исследователь)"),
                    ("researcher", "Researcher (Исследователь)"),
                    ("analyst", "Analyst (Аналитик)"),
                    ("writer", "Writer (Автор текста)"),
                    ("reviewer", "Reviewer (Рецензент)"),
                    ("editor", "Editor (Редактор)"),
                    ("assistant", "Assistant (Ассистент)"),
                    ("viewer", "Viewer (Наблюдатель)"),
                ],
                default="researcher",
                max_length=50,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название спринта"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Планирование"),
                            ("active", "Активный"),
                            ("completed", "Завершен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                ("goal", models.TextField(verbose_name="Цель спринта")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спринт",
                "verbose_name_plural": "Спринты",
                "ordering": ["start_date"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="current_sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_in_projects",
                to="projects.sprint",
                verbose_name="Текущий спринт",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название задачи"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Бэклог"),
                            ("todo", "К выполнению"),
                            ("in_progress", "В работе"),
                            ("review", "На проверке"),
                            ("done", "Выполнено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="backlog",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Срок выполнения"
                    ),
                ),
                (
                    "estimated_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Оценка в часах"
                    ),
                ),
                (
                    "actual_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Фактические часы"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="projects.sprint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["priority", "due_date", "created_at"],
            },
        ),
    ]
