# Generated by Django 5.2.7 on 2026-01-30 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_options_alter_projectmember_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["position", "-priority", "due_date", "created_at"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="Позиция"),
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="Теги"),
        ),
        migrations.AlterField(
            model_name="collaborationmatch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="collaborationmatch",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="collaborationmatch",
            name="user_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_matches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="От пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="collaborationmatch",
            name="user_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_matches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="К пользователю",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="joined_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата вступления"
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="projects.project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sprints",
                to="projects.project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Планирование"),
                    ("active", "Активный"),
                    ("completed", "Завершен"),
                    ("cancelled", "Отменен"),
                ],
                default="planning",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Низкий"),
                    ("medium", "Средний"),
                    ("high", "Высокий"),
                    ("critical", "Критический"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Приоритет",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="projects.sprint",
                verbose_name="Спринт",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Бэклог"),
                    ("todo", "К выполнению"),
                    ("in_progress", "В работе"),
                    ("review", "На проверке"),
                    ("done", "Выполнено"),
                    ("cancelled", "Отменено"),
                ],
                default="backlog",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
