# Generated by Django 5.2.7 on 2026-02-11 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0003_alter_task_options_task_completed_at_task_position_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("product_owner", "Product Owner (Научный руководитель)"),
                    ("scrum_master", "Scrum Master (Менжер проекта)"),
                    ("lead_researcher", "Lead Researcher (Ведущий исследователь)"),
                    ("researcher", "Researcher (Исследователь)"),
                    ("analyst", "Analyst (Аналитик)"),
                    ("writer", "Writer (Автор текста)"),
                    ("reviewer", "Reviewer (Рецензент)"),
                    ("editor", "Editor (Редактор)"),
                    ("assistant", "Assistant (Ассистент)"),
                    ("viewer", "Viewer (Наблюдатель)"),
                ],
                default="researcher",
                max_length=50,
                verbose_name="Роль",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата редактирования"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="projects.comment",
                        verbose_name="Родительский комментарий",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "created_at"],
                        name="projects_co_task_id_769071_idx",
                    ),
                    models.Index(
                        fields=["author", "created_at"],
                        name="projects_co_author__e774f7_idx",
                    ),
                ],
            },
        ),
    ]
