# Generated by Django 5.2.7 on 2026-02-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_projectmember_role_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("product_owner", "Product Owner (Научный руководитель)"),
                    ("scrum_master", "Scrum Master (Менеджер проекта)"),
                    ("lead_researcher", "Lead Researcher (Ведущий исследователь)"),
                    ("researcher", "Researcher (Исследователь)"),
                    ("analyst", "Analyst (Аналитик)"),
                    ("writer", "Writer (Автор текста)"),
                    ("reviewer", "Reviewer (Рецензент)"),
                    ("editor", "Editor (Редактор)"),
                    ("assistant", "Assistant (Ассистент)"),
                    ("viewer", "Viewer (Наблюдатель)"),
                ],
                default="researcher",
                max_length=50,
                verbose_name="Роль",
            ),
        ),
    ]
