# Generated by Django 5.2.7 on 2026-02-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_comment_options_alter_projectmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="attachments",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список прикрепленных файлов",
                verbose_name="Вложения",
            ),
        ),
    ]
