# Generated by Django 5.2.7 on 2026-02-13 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_comment_attachments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="Текстовое содержимое сообщения",
                        verbose_name="Текст сообщения",
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список прикрепленных файлов в формате JSON",
                        verbose_name="Вложения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата редактирования"
                    ),
                ),
                (
                    "read_by",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список ID пользователей, которые прочитали это сообщение",
                        verbose_name="Прочитано пользователями",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="projects.projectchatmessage",
                        verbose_name="Ответ на сообщение",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение чата",
                "verbose_name_plural": "Сообщения чата",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "created_at"],
                        name="projects_pr_project_aaea49_idx",
                    ),
                    models.Index(
                        fields=["author", "created_at"],
                        name="projects_pr_author__253e44_idx",
                    ),
                    models.Index(
                        fields=["parent_message"], name="projects_pr_parent__16c49a_idx"
                    ),
                ],
            },
        ),
    ]
