# Generated by Django 5.2.7 on 2026-02-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_add_project_chat_message_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="conference_link",
            field=models.CharField(
                blank=True,
                help_text="Автоматически создаётся при создании проекта через VK API",
                max_length=500,
                null=True,
                verbose_name="Ссылка на конференцию VK",
            ),
        ),
    ]
