# Generated by Django 5.2.7 on 2026-02-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_add_conference_link_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="total_sprints",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Общее количество спринтов, запланированных для проекта",
                verbose_name="Всего спринтов",
            ),
        ),
    ]
