# Generated by Django 5.2.7 on 2026-02-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_total_sprints"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sprint_titles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список названий спринтов в порядке их выполнения",
                verbose_name="Названия спринтов",
            ),
        ),
    ]
