# Generated by Django 5.2.7 on 2026-02-22 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_project_sprint_titles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="project_documents/%Y/%m/%d/", verbose_name="Файл"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название файла"),
                ),
                (
                    "size",
                    models.PositiveIntegerField(verbose_name="Размер файла (байты)"),
                ),
                (
                    "extension",
                    models.CharField(max_length=50, verbose_name="Расширение"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ проекта",
                "verbose_name_plural": "Документы проекта",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
