# Generated by Django 5.2.7 on 2026-03-05 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_projectdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmember",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Участник проекта",
                "verbose_name_plural": "Участники проектов",
            },
        ),
        migrations.AddField(
            model_name="projectmember",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата подачи заявки",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectmember",
            name="invited_by_old",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_project_members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Приглашен пользователем (старое поле)",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="joined_at_old",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата вступления (старое поле)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectmember",
            name="message",
            field=models.TextField(blank=True, verbose_name="Сопроводительное письмо"),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="Причина отказа"),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата рассмотрения"
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_reviews_done",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Рассмотрел",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает подтверждения"),
                    ("approved", "Участник"),
                    ("rejected", "Отклонен"),
                    ("cancelled", "Отменено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_invitations_sent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пригласил",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="joined_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата вступления"
            ),
        ),
    ]
