# Generated by Django 5.2.7 on 2026-03-07 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0012_alter_projectmember_options_projectmember_created_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="collaborationmatch",
            index=models.Index(
                fields=["user_from", "match_score"],
                name="projects_co_user_fr_3474a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationmatch",
            index=models.Index(
                fields=["user_to", "match_score"], name="projects_co_user_to_54af99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["task", "author"], name="projects_co_task_id_083f60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent_comment"], name="projects_co_parent__2be5fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "created_at"], name="projects_pr_status_7ee874_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "status"], name="projects_pr_owner_i_4798b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_private", "status"], name="projects_pr_is_priv_16c8bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectchatmessage",
            index=models.Index(
                fields=["project", "author"], name="projects_pr_project_6bb026_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectchatmessage",
            index=models.Index(
                fields=["project", "-created_at"], name="projects_pr_project_064bfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectdocument",
            index=models.Index(
                fields=["project", "uploaded_at"], name="projects_pr_project_146a2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectdocument",
            index=models.Index(
                fields=["uploaded_by", "uploaded_at"],
                name="projects_pr_uploade_12d439_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["project", "status"], name="projects_pr_project_3f16c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["user", "status"], name="projects_pr_user_id_3f6dd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["status", "created_at"], name="projects_pr_status_e8b00a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["project", "status"], name="projects_sp_project_b718db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["project", "start_date"], name="projects_sp_project_6bd741_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["status", "start_date"], name="projects_sp_status_7cb83d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "status"], name="projects_ta_project_cd2085_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["sprint", "status"], name="projects_ta_sprint__0d0620_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assignee", "status"], name="projects_ta_assigne_df8978_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["due_date", "status"], name="projects_ta_due_dat_d97d19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "sprint"], name="projects_ta_project_564e28_idx"
            ),
        ),
    ]
