# Generated by Django 5.2.7 on 2026-02-23 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0011_projectdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                ("description", models.TextField(verbose_name="Полное описание")),
                (
                    "short_description",
                    models.CharField(
                        help_text="Для карточки мероприятия",
                        max_length=300,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("conference", "Конференция"),
                            ("seminar", "Семинар"),
                            ("symposium", "Симпозиум"),
                            ("workshop", "Воркшоп"),
                            ("school", "Школа"),
                            ("congress", "Конгресс"),
                            ("forum", "Форум"),
                            ("roundtable", "Круглый стол"),
                            ("competition", "Конкурс"),
                            ("festival", "Фестиваль"),
                        ],
                        max_length=50,
                        verbose_name="Тип мероприятия",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("international", "Международный"),
                            ("national", "Всероссийский"),
                            ("interregional", "Межрегиональный"),
                            ("regional", "Региональный"),
                            ("university", "Внутривузовский"),
                        ],
                        max_length=50,
                        verbose_name="Уровень мероприятия",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "registration_deadline",
                    models.DateField(verbose_name="Дедлайн регистрации"),
                ),
                (
                    "organizer_branches",
                    models.JSONField(
                        default=list,
                        help_text="Список названий филиалов из справочника",
                        verbose_name="Филиалы-организаторы",
                    ),
                ),
                (
                    "cover_images",
                    models.JSONField(
                        default=list,
                        help_text="Массив путей к изображениям для карусели",
                        verbose_name="Изображения обложки",
                    ),
                ),
                (
                    "documents",
                    models.JSONField(
                        default=list,
                        help_text="Массив {name, url, size, extension}",
                        verbose_name="Документы мероприятия",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        help_text="Будет отображаться в текстовой витрине",
                        verbose_name="Дополнительная информация",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("published", "Опубликовано"),
                            ("registration_closed", "Регистрация закрыта"),
                            ("in_progress", "Идёт мероприятие"),
                            ("completed", "Завершено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "has_sections",
                    models.BooleanField(
                        default=False,
                        help_text="Определяет вариант отображения страницы",
                        verbose_name="Есть секции",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название секции"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание секции"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4CAF50",
                        max_length=7,
                        verbose_name="Цвет карточки (HEX)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="conferences.event",
                        verbose_name="Мероприятие",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Должен быть преподавателем или сотрудником",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_sections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Модератор секции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Секция",
                "verbose_name_plural": "Секции",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participation_type",
                    models.CharField(
                        choices=[
                            ("listener", "Слушатель"),
                            ("speaker", "Выступающий/докладчик"),
                            ("organizer", "Организатор"),
                            ("moderator", "Модератор"),
                        ],
                        max_length=20,
                        verbose_name="Тип участия",
                    ),
                ),
                (
                    "uploaded_files",
                    models.JSONField(
                        default=list,
                        help_text="Массив {name, url, size, extension}",
                        verbose_name="Загруженные файлы",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("approved", "Подтверждено"),
                            ("rejected", "Отклонено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, verbose_name="Комментарий к решению"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата подачи"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="conferences.event",
                        verbose_name="Мероприятие",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Проект, который участник представляет на мероприятии",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.project",
                        verbose_name="Связанный проект",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Рассмотрел",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Для выступающих обязательно, для слушателей опционально",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conferences.section",
                        verbose_name="Секция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник мероприятия",
                "verbose_name_plural": "Участники мероприятий",
                "ordering": ["-created_at"],
                "unique_together": {("event", "user")},
            },
        ),
        migrations.CreateModel(
            name="EventNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок новости"),
                ),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "media",
                    models.JSONField(
                        default=list,
                        help_text="Массив {type: 'image/video', url: '...', thumbnail: '...'}",
                        verbose_name="Медиафайлы",
                    ),
                ),
                (
                    "video_plays_automuted",
                    models.BooleanField(
                        default=True,
                        verbose_name="Видео с автовоспроизведением без звука",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_news",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="conferences.event",
                        verbose_name="Мероприятие",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если новость относится к конкретной секции",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="conferences.section",
                        verbose_name="Секция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость мероприятия",
                "verbose_name_plural": "Новости мероприятий",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpeakerMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название материала"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "files",
                    models.JSONField(
                        default=list,
                        help_text="Массив {name, url, size, extension}",
                        verbose_name="Файлы",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Если False, видят только организаторы и модераторы",
                        verbose_name="Публичный доступ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="conferences.eventparticipant",
                        verbose_name="Участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал выступающего",
                "verbose_name_plural": "Материалы выступающих",
                "ordering": ["-created_at"],
            },
        ),
    ]
