# Generated by Django 5.2.7 on 2026-02-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, verbose_name="Полное описание"),
        ),
    ]
