# Generated by Django 5.2.7 on 2026-02-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0002_alter_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="conference_link",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Ссылка на конференцию секции",
            ),
        ),
    ]
