# Generated by Django 5.2.7 on 2026-02-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0003_section_conference_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="conference_link",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Ссылка на конференцию мероприятия",
            ),
        ),
    ]
