# Generated by Django 5.2.7 on 2026-02-26 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0004_event_conference_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="moderator",
        ),
        migrations.AddField(
            model_name="event",
            name="organizers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Пользователи, которые являются организаторами мероприятия (кроме создателя)",
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Организаторы",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="moderators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Пользователи, которые являются модераторами этой секции",
                related_name="moderated_sections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Модераторы секции",
            ),
        ),
    ]
