# Generated by Django 5.2.7 on 2026-02-26 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0005_remove_section_moderator_event_organizers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="plenary_moderators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Пользователи, которые являются модераторами пленарного заседания",
                related_name="plenary_moderated_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Модераторы пленарного заседания",
            ),
        ),
    ]
