# Generated by Django 5.2.7 on 2026-02-26 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0006_event_plenary_moderators"),
        ("projects", "0011_projectdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="additional_info",
            field=models.TextField(
                blank=True, verbose_name="Дополнительная информация"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="has_sections",
            field=models.BooleanField(default=False, verbose_name="Есть секции"),
        ),
        migrations.AlterField(
            model_name="eventnews",
            name="media",
            field=models.JSONField(default=list, verbose_name="Медиафайлы"),
        ),
        migrations.AlterField(
            model_name="eventnews",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="conferences.section",
                verbose_name="Секция",
            ),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="participation_type",
            field=models.CharField(
                choices=[
                    ("speaker", "Выступающий/докладчик"),
                    ("listener", "Слушатель"),
                ],
                max_length=20,
                verbose_name="Тип участия",
            ),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.project",
                verbose_name="Связанный проект",
            ),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="uploaded_files",
            field=models.JSONField(default=list, verbose_name="Загруженные файлы"),
        ),
        migrations.AlterField(
            model_name="section",
            name="moderators",
            field=models.ManyToManyField(
                blank=True,
                related_name="moderated_sections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Модераторы секции",
            ),
        ),
        migrations.AlterField(
            model_name="speakermaterial",
            name="files",
            field=models.JSONField(default=list, verbose_name="Файлы"),
        ),
        migrations.AlterField(
            model_name="speakermaterial",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Публичный доступ"),
        ),
    ]
