# Generated by Django 5.2.7 on 2026-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conferences",
            "0007_alter_event_additional_info_alter_event_has_sections_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="talk_title",
            field=models.CharField(
                blank=True,
                help_text="Название или тема выступления (для докладчиков)",
                max_length=500,
                verbose_name="Тема доклада",
            ),
        ),
    ]
