# Generated by Django 5.2.7 on 2026-02-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0008_eventparticipant_talk_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="is_plenary",
            field=models.BooleanField(
                default=False,
                help_text="True для докладчиков на пленарном заседании, False для секционных докладчиков",
                verbose_name="Пленарное заседание",
            ),
        ),
    ]
