# Generated by Django 5.2.7 on 2026-02-28 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0009_eventparticipant_is_plenary"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_plenary",
                    models.BooleanField(
                        default=False,
                        help_text="True для пунктов пленарного заседания",
                        verbose_name="Пленарное заседание",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Для организационных блоков (регистрация, кофе-брейк и т.д.)",
                        max_length=300,
                        verbose_name="Название блока",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("start_time", models.DateTimeField(verbose_name="Время начала")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Для сортировки внутри секции или пленарного заседания",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Участник с типом 'speaker' и статусом 'approved'",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_items",
                        to="conferences.eventparticipant",
                        verbose_name="Выступающий",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="conferences.section",
                        verbose_name="Секция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт программы",
                "verbose_name_plural": "Пункты программы",
                "ordering": ["start_time", "order"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_plenary", False), ("section__isnull", False)),
                            models.Q(("is_plenary", True), ("section__isnull", True)),
                            _connector="OR",
                        ),
                        name="either_section_or_plenary",
                    )
                ],
            },
        ),
    ]
