# Generated by Django 5.2.7 on 2026-02-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0010_scheduleitem"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scheduleitem",
            name="either_section_or_plenary",
        ),
        migrations.AlterField(
            model_name="scheduleitem",
            name="is_plenary",
            field=models.BooleanField(
                default=False, verbose_name="Пленарное заседание"
            ),
        ),
        migrations.AlterField(
            model_name="scheduleitem",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Для сортировки", verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="scheduleitem",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedule_items",
                to="conferences.eventparticipant",
                verbose_name="Выступающий",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_plenary", True), ("section__isnull", True)),
                    models.Q(("is_plenary", False), ("section__isnull", False)),
                    models.Q(
                        ("is_plenary", False),
                        ("section__isnull", True),
                        ("title__gt", ""),
                    ),
                    _connector="OR",
                ),
                name="either_section_or_plenary",
            ),
        ),
    ]
