# Generated by Django 5.2.7 on 2026-02-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0011_remove_scheduleitem_either_section_or_plenary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_items",
                to="conferences.event",
                verbose_name="Мероприятие",
            ),
        ),
    ]
