# Generated by Django 5.2.7 on 2026-03-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0012_scheduleitem_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="speaker_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Порядковый номер докладчика (0 - первый, 1 - второй и т.д.)",
                verbose_name="Порядок выступления",
            ),
        ),
    ]
