# Generated by Django 5.2.7 on 2026-03-01 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0013_eventparticipant_speaker_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventnews",
            name="excerpt",
            field=models.CharField(
                blank=True,
                help_text="Краткий текст для предпросмотра (если не заполнено, берется из начала content)",
                max_length=300,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AddField(
            model_name="eventnews",
            name="likes_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество лайков"
            ),
        ),
        migrations.AddField(
            model_name="eventnews",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="eventnews",
            name="media",
            field=models.JSONField(
                default=list,
                help_text="Массив объектов {type: 'image/video', url: '...', thumbnail: '...'}",
                verbose_name="Медиафайлы",
            ),
        ),
        migrations.AlterField(
            model_name="eventnews",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Если не выбрана - новость общая для всего мероприятия",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="conferences.section",
                verbose_name="Секция",
            ),
        ),
    ]
