# Generated by Django 5.2.7 on 2026-03-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0014_eventnews_excerpt_eventnews_likes_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="cover_images",
            field=models.JSONField(
                default=list,
                help_text="Массив путей к изображениям для карусели",
                verbose_name="Изображения обложки секции",
            ),
        ),
    ]
