# Generated by Django 5.2.7 on 2026-03-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0015_section_cover_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="about",
            field=models.TextField(
                blank=True,
                help_text="Текст для блока 'О секции' на странице секции",
                verbose_name="Подробная информация о секции",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="description",
            field=models.TextField(
                blank=True, verbose_name="Краткое описание для шапки"
            ),
        ),
    ]
