"""
Django settings for collaboration_platform project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import re  # 🔥 Импорт для функции fixer (уже был)
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-j)gc_+hy^u29^tmdww2qt*r5#0wf$93%grg%sr#!o18xd(eavn"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'users',  # ДОЛЖНО БЫТЬ ПЕРВЫМ!
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Сторонние приложения
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'social_django',

    # Наши приложения
    'questionnaires',
    'projects',
    'conferences',
    'invitations',
    'notifications',
]

# Указываем кастомную модель пользователя
AUTH_USER_MODEL = 'users.CustomUser'

# Настройки медиа файлов (для аватарок)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "collaboration_platform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "collaboration_platform.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Дополнительные настройки для локализации
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Настройки REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# Настройки JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Настройки CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_ALL_ORIGINS = True  # Временно для разработки
CORS_ALLOW_CREDENTIALS = True

# Разрешаем все заголовки
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ========================================
# 🔥 НОВОЕ: НАСТРОЙКИ ДЛЯ ЗАГРУЗКИ ФАЙЛОВ
# ========================================


# Максимальный размер файла (10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760   # 10 * 1024 * 1024

# Разрешенные расширения файлов
ALLOWED_FILE_EXTENSIONS = [
    # Документы
    '.pdf', '.doc', '.docx', '.xls', '.xlsx',
    '.ppt', '.pptx', '.txt', '.md', '.rtf',
    # Изображения
    '.jpg', '.jpeg', '.png', '.gif', '.bmp', '.svg', '.webp',
    # Архивы
    '.zip', '.rar', '.7z', '.tar', '.gz',
    # Код и данные
    '.py', '.js', '.html', '.css', '.json', '.xml', '.csv',
]

# Максимальное количество файлов в одном комментарии
MAX_ATTACHMENTS_PER_COMMENT = 5

# Размер иконки для изображений (будет создаваться миниатюра)
THUMBNAIL_SIZE = (200, 200)

# ========================================
# VK ID SETTINGS - СТАРЫЕ РАБОЧИЕ
# ========================================
SOCIAL_AUTH_VK_OAUTH2_KEY = '54454413'
SOCIAL_AUTH_VK_OAUTH2_SECRET = 'uw0BJzPlVJXWjp7rHlhd'

# Важно: правильная область видимости
SOCIAL_AUTH_VK_OAUTH2_SCOPE = ['email', 'photos']

# Эти параметры заставят VK отдавать email
SOCIAL_AUTH_VK_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'v': '5.199',
    'revoke': 1,
    'response_type': 'code'
}

# Дополнительные данные, которые сохраняем от VK
SOCIAL_AUTH_VK_OAUTH2_EXTRA_DATA = [
    ('email', 'email'),
    ('access_token', 'access_token'),
    ('user_id', 'user_id'),
    ('expires_in', 'expires_in')
]

# Разрешаем привязку по email
SOCIAL_AUTH_ASSOCIATE_BY_MAIL = True

# Поля, которые используем для создания/обновления пользователя
SOCIAL_AUTH_USER_FIELDS = ['email', 'username', 'first_name', 'last_name']
SOCIAL_AUTH_VK_OAUTH2_USERNAME_IS_FULL_EMAIL = False

def social_username_from_email(email):
    if email:
        username = email.split('@')[0].replace('.', '_')
        username = re.sub(r'[^\w]', '_', username)
        return username
    return None

SOCIAL_AUTH_USERNAME_FIXER = social_username_from_email

# ============================================
# EMAIL SETTINGS
# ============================================

# Для разработки (вывод писем в консоль)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Для продакшена (раскомментировать и настроить)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  # или ваш SMTP сервер
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'noreply@finuniversity.ru'
# EMAIL_HOST_PASSWORD = 'your-password'
# DEFAULT_FROM_EMAIL = 'Научная коллаборация <noreply@finuniversity.ru>'

# Базовый URL сайта для ссылок в письмах
SITE_URL = 'http://localhost:3000'  # для разработки
# SITE_URL = 'https://your-domain.ru'  # для продакшена