# Generated by Django 5.2.7 on 2026-02-18 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="respondent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaire_responses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Респондент",
            ),
        ),
    ]
