# Generated by Django 5.2.7 on 2026-02-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("product_owner", "Product Owner (Научный руководитель)"),
                    ("scrum_master", "Scrum Master (Менеджер проекта)"),
                    ("lead_researcher", "Lead Researcher (Ведущий исследователь)"),
                    ("researcher", "Researcher (Исследователь)"),
                    ("analyst", "Analyst (Аналитик)"),
                    ("writer", "Writer (Автор текста)"),
                    ("reviewer", "Reviewer (Рецензент)"),
                    ("editor", "Editor (Редактор)"),
                    ("assistant", "Assistant (Ассистент)"),
                    ("viewer", "Viewer (Наблюдатель)"),
                ],
                default="researcher",
                max_length=50,
                verbose_name="Роль в проекте",
            ),
        ),
    ]
