# Generated by Django 5.2.7 on 2026-03-06 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conferences", "0016_section_about_alter_section_description"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("invitations", "0002_invitation_role"),
        (
            "projects",
            "0012_alter_projectmember_options_projectmember_created_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("invitation_received", "Приглашение в проект"),
                            ("invitation_accepted", "Приглашение принято"),
                            ("invitation_rejected", "Приглашение отклонено"),
                            ("invitation_cancelled", "Приглашение отменено"),
                            ("project_join_request", "Заявка на вступление"),
                            ("project_join_approved", "Заявка одобрена"),
                            ("project_join_rejected", "Заявка отклонена"),
                            ("task_assigned", "Назначена задача"),
                            ("task_completed", "Задача выполнена"),
                            ("task_updated", "Задача обновлена"),
                            ("task_comment", "Новый комментарий к задаче"),
                            ("event_registration_open", "Открыта регистрация"),
                            ("event_reminder", "Напоминание о мероприятии"),
                            ("event_participation_request", "Заявка на участие"),
                            ("event_participation_approved", "Заявка одобрена"),
                            ("event_participation_rejected", "Заявка отклонена"),
                            ("event_schedule_changed", "Изменение в программе"),
                            ("system_announcement", "Объявление"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Тип уведомления",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("message", models.TextField(verbose_name="Текст уведомления")),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "action_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="URL для перехода"
                    ),
                ),
                (
                    "action_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Дополнительные данные для действия",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Прочитано"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="В архиве"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата прочтения"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="conferences.event",
                    ),
                ),
                (
                    "event_participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="conferences.eventparticipant",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="invitations.invitation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="projects.project",
                    ),
                ),
                (
                    "project_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="projects.projectmember",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["recipient", "type"],
                        name="notificatio_recipie_036988_idx",
                    ),
                ],
            },
        ),
    ]
